name: ci

on:
  push:
    paths-ignore:
      - "/*.md"
      - "ctests/**"
  pull_request:
    paths-ignore:
      - "/*.md"
      - "ctests/**"

jobs:
  rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install stable toolchain
        run: rustup toolchain install stable --profile minimal

      - name: cargo check
        run: cargo +stable check --all-features

      - name: cargo test
        run: cargo +stable test --all-features

      - name: cargo clippy
        run: cargo +stable clippy
